"use strict";
'use client';
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const toaster_1 = require("@/components/ui/toaster");
const navbar_1 = require("@/components/features/layouts/navbar");
const sidebar_1 = require("@/components/features/layouts/sidebar");
const navigation_1 = require("next/navigation");
const inter = (0, google_1.Inter)({ subsets: ['latin'] });
// export const metadata: Metadata = {
//   title: "ERP",
//   description: "Generated by create next app",
// };
function RootLayout({ children, }) {
    const router = (0, navigation_1.usePathname)();
    return (<html lang="en">
      <head>
        <title>ERP B</title>
      </head>
      <body className={inter.className}>
        <toaster_1.Toaster />
        {router !== '/login' &&
            router !== '/signup' &&
            router !== '/verify' &&
            router !== '/reset' &&
            router !== '/auth/callback' &&
            router !== '/forget' ? (<div className="flex min-h-screen w-full">
            {
            // Hide sidebar on login and signup page
            <div className="fixed left-0 top-0 h-screen w-[240px] border-r border-gray-200 bg-white shadow-lg z-10 overflow-y-auto">
                <sidebar_1.default />
              </div>}

            {/* Main Content Area */}
            <div className="ml-[240px] flex flex-1 flex-col">
              {/* Navbar */}
              <div className="w-full">
                <navbar_1.default />
              </div>

              {/* Children Content */}
              <main className="flex-1 overflow-auto p-4 -mt-16">
                {children}
              </main>
            </div>
          </div>) : (<main className="">{children}</main>)}
      </body>
    </html>);
}
