'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Toaster } from '@/components/ui/toaster'
import Navbar from '@/components/features/layouts/navbar'
import SideBar from '@/components/features/layouts/sidebar'
import { NextRequest } from 'next/server'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "ERP",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const router = usePathname()

  return (
    <html lang="en">
      <head>
        <title>ERP N</title>
      </head>
      <body className={inter.className}>
        <Toaster />
        {router !== '/login' &&
        router !== '/signup' &&
        router !== '/verify' &&
        router !== '/reset' &&
        router !== '/auth/callback' &&
        router !== '/forget' ? (
          <div className="flex min-h-screen w-full">
            {
              // Hide sidebar on login and signup page

              <div className="fixed left-0 top-0 h-screen w-[240px] border-r border-gray-200 bg-white shadow-lg z-10 overflow-y-auto">
                <SideBar />
              </div>
            }

            {/* Main Content Area */}
            <div className="ml-[240px] flex flex-1 flex-col">
              {/* Navbar */}
              <div className="w-full">
                <Navbar />
              </div>

              {/* Children Content */}
              <main className="flex-1 overflow-auto p-4 -mt-16">
                {children}
              </main>
            </div>
          </div>
        ) : (
          <main className="">{children}</main>
        )}
      </body>
    </html>
  )
}
