"use strict";
'use client';
Object.defineProperty(exports, "__esModule", { value: true });
exports.Separator = void 0;
const React = require("react");
const SeparatorPrimitive = require("@radix-ui/react-separator");
const utils_1 = require("@/lib/utils");
const Separator = React.forwardRef(({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (<SeparatorPrimitive.Root ref={ref} decorative={decorative} orientation={orientation} className={(0, utils_1.cn)('shrink-0 bg-border', orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]', className)} {...props}/>));
exports.Separator = Separator;
Separator.displayName = SeparatorPrimitive.Root.displayName;
