"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoomSelectionView = exports.CalendarScreen = exports.RoomSelection = exports.BookingPage = exports.Index = exports.Hello = exports.Tests = exports.MyButtonComponent = void 0;
require("./index.css");
const Button_1 = __importDefault(require("./components/Button"));
exports.MyButtonComponent = Button_1.default;
const BookingForm_1 = __importDefault(require("./components/BookingForm"));
exports.Tests = BookingForm_1.default;
const Hello_1 = __importDefault(require("./components/Hello"));
exports.Hello = Hello_1.default;
const Home_component_1 = __importDefault(require("./components/Home/Home-component"));
exports.Index = Home_component_1.default;
const BookingPage_1 = __importDefault(require("./components/Home/BookingPage"));
exports.BookingPage = BookingPage_1.default;
const RoomSelection_1 = __importDefault(require("./components/Home/RoomSelection"));
exports.RoomSelection = RoomSelection_1.default;
const RoomSectionView_1 = __importDefault(require("./components/Home/RoomSectionView"));
exports.RoomSelectionView = RoomSectionView_1.default;
const CalendarScreen_1 = __importDefault(require("./components/Home/CalendarScreen"));
exports.CalendarScreen = CalendarScreen_1.default;
